### ISSUE TITLE
MSVC build broken

### ISSUE THREAD

**Issue by Fighter19** [OGRECave/ogitor#14]
When building with MSVC (14.1 / 2017)
an error occurs, as the classes imported via dllimport have static members.

error C2491: "Ogitors::CBillboardSetEditorFactory::mBillboardTypes": definition of dllimport function for static members not allowed

(Not the actual message, but translated)

**Comment by kPYKx7Ddw4n1aIKZ** [comment]
I can reproduce this issue and I found out that it is caused by this lines:
https://github.com/OGRECave/ogitor/blob/b4440579c2b15340085cb03f021b5918512fe3fa/Ogitor/include/OgitorsExports.h#L35-L47
`OGITOR_EXPORT` isn't defined anywhere, so every `OgitorExport` declaration is replaced with `__declspec (dllimport)` even when building Ogitor, which is wrong.
Either one could just define it using [COMPILE_DEFINITIONS](https://cmake.org/cmake/help/latest/prop_sf/COMPILE_DEFINITIONS.html) or change the [DEFINE_SYMBOL](https://cmake.org/cmake/help/latest/prop_tgt/DEFINE_SYMBOL.html) which does something similar but defines [`Ogitor_EXPORTS`](https://stackoverflow.com/questions/27429732/cmake-adds-dlibname-exports-compile-definition) instead by default.

**Comment by paroj** [comment]
in ogre I ported most of the modules to https://cmake.org/cmake/help/latest/module/GenerateExportHeader.html

however with ogitor we should aim to get it into a usable state first. Checking for `#ifdef Ogitor_EXPORTS` is probably the fastest way to get there.

**Comment by paroj** [comment]
fixed by #16
